{{- if .Values.enable.dex }}
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeflow-dex
  namespace: {{ .Values.namespaces.project }}
spec:
  interval: {{ .Values.kustomizations.intervals.default }}
  timeout: {{ .Values.kustomizations.timeouts.medium }}
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  path: ./common/dex/overlays/oauth2-proxy
  targetNamespace: {{ .Values.namespaces.auth }}
  dependsOn:
    - name: kubeflow-istio-resources
  patchesJson6902:
    - target:
        version: v1
        kind: ConfigMap
        name: dex
      patch:
        - op: replace
          path: /data/config.yaml
          value: |
            issuer: {{ .Values.dex.issuerUrl }}
            storage:
              type: kubernetes
              config:
                inCluster: true
            web:
              http: 0.0.0.0:5556
            logger:
              level: "debug"
              format: text
            oauth2:
              skipApprovalScreen: true
            enablePasswordDB: true
            staticPasswords:
            - email: user@example.com
              hashFromEnv: DEX_USER_PASSWORD
              username: user
              userID: "15841185641784"
            staticClients:
            # https://github.com/dexidp/dex/pull/1664
            - idEnv: OIDC_CLIENT_ID
              redirectURIs: ["/oauth2/callback"]
              name: 'Dex Login Application'
              secretEnv: OIDC_CLIENT_SECRET
            connectors:
            {{- range .Values.dex.connectors }}
            - type: {{ .type }}
              id: {{ .id }}
              name: {{ .name | quote }}
              config:
                issuer: {{ .config.issuer }}
                {{- if .config.issuerAlias }}
                issuerAlias: {{ .config.issuerAlias }}
                {{- end }}
                redirectURI: {{ .config.redirectURI }}
                clientID: {{ .config.clientID }}
                clientSecret: {{ .config.clientSecret }}
                {{- if .config.insecureSkipEmailVerified }}
                insecureSkipEmailVerified: {{ .config.insecureSkipEmailVerified }}
                {{- end }}
                {{- if .config.getUserInfo }}
                getUserInfo: {{ .config.getUserInfo }}
                {{- end }}
                {{- if .config.overrideClaimMapping }}
                overrideClaimMapping: {{ .config.overrideClaimMapping }}
                {{- end }}
                {{- if .config.claimMapping }}
                claimMapping:
                  {{- range $k, $v := .config.claimMapping }}
                  {{ $k }}: {{ $v }}
                  {{- end }}
                {{- end }}
                scopes:
                {{- range .config.scopes }}
                - {{ . }}
                {{- end }}
            {{- end }}
    - target:
        group: apps
        version: v1
        kind: Deployment
        name: dex
      patch:
        - op: add
          path: /spec/template/spec/containers/0/envFrom/-
          value:
            secretRef:
              name: {{ .Values.namespaces.project }}
        - op: replace
          path: /spec/template/spec/containers/0/image
          value: ghcr.io/dexidp/dex:v2.44.0
        {{- if .Values.dex.customUI.enabled }}
        - op: add
          path: /spec/template/spec/volumes/-
          value:
            name: dex-custom-templates
            configMap:
              name: dex-custom-templates
        - op: add
          path: /spec/template/spec/containers/0/volumeMounts/-
          value:
            name: dex-custom-templates
            mountPath: /srv/dex/web/templates/header.html
            subPath: header.html
        {{- end }}
{{- if .Values.dex.customUI.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-custom-templates
  namespace: {{ .Values.namespaces.auth }}
data:
  header.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{{"{{ .Issuer }}"}}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="{{"{{ theme \"styles.css\" }}"}}" rel="stylesheet">
        <link href="{{"{{ theme \"favicon.png\" }}"}}" rel="icon">
        {{- if .Values.dex.customUI.css }}
        <style>
{{ .Values.dex.customUI.css | indent 10 }}
        </style>
        {{- end }}
      </head>
      <body class="theme-body">
{{- end }}
{{- end }}
