{{- if .Values.enable.notebooks }}
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeflow-volumes-web-app
  namespace: {{ .Values.namespaces.project }}
spec:
  interval: {{ .Values.kustomizations.intervals.default }}
  timeout: {{ .Values.kustomizations.timeouts.medium }}
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  path: ./apps/volumes-web-app/upstream/overlays/istio
  targetNamespace: {{ .Values.namespaces.kubeflow }}
  dependsOn:
    - name: kubeflow-profiles
    - name: kubeflow-istio-resources
{{- end }}
